services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: gustav
      POSTGRES_PASSWORD: mahler
      POSTGRES_DB: mahlearn
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
